/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	mobile_v1alpha1 "github.com/aerogear/mobile-crd-client/pkg/apis/mobile/v1alpha1"
	versioned "github.com/aerogear/mobile-crd-client/pkg/client/mobile/clientset/versioned"
	internalinterfaces "github.com/aerogear/mobile-crd-client/pkg/client/mobile/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/aerogear/mobile-crd-client/pkg/client/mobile/listers/mobile/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// MobileClientInformer provides access to a shared informer and lister for
// MobileClients.
type MobileClientInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MobileClientLister
}

type mobileClientInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMobileClientInformer constructs a new informer for MobileClient type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMobileClientInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMobileClientInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMobileClientInformer constructs a new informer for MobileClient type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMobileClientInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MobileV1alpha1().MobileClients(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MobileV1alpha1().MobileClients(namespace).Watch(options)
			},
		},
		&mobile_v1alpha1.MobileClient{},
		resyncPeriod,
		indexers,
	)
}

func (f *mobileClientInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMobileClientInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *mobileClientInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&mobile_v1alpha1.MobileClient{}, f.defaultInformer)
}

func (f *mobileClientInformer) Lister() v1alpha1.MobileClientLister {
	return v1alpha1.NewMobileClientLister(f.Informer().GetIndexer())
}
