/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package internalversion

import (
	mobile "github.com/aerogear/mobile-crd-client/pkg/apis/mobile"
	clientset_internalversion "github.com/aerogear/mobile-crd-client/pkg/client/mobile/clientset/internalversion"
	internalinterfaces "github.com/aerogear/mobile-crd-client/pkg/client/mobile/informers/internalversion/internalinterfaces"
	internalversion "github.com/aerogear/mobile-crd-client/pkg/client/mobile/listers/mobile/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// ClientInformer provides access to a shared informer and lister for
// Clients.
type ClientInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.ClientLister
}

type clientInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClientInformer constructs a new informer for Client type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClientInformer(client clientset_internalversion.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClientInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClientInformer constructs a new informer for Client type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClientInformer(client clientset_internalversion.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Mobile().Clients(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Mobile().Clients(namespace).Watch(options)
			},
		},
		&mobile.Client{},
		resyncPeriod,
		indexers,
	)
}

func (f *clientInformer) defaultInformer(client clientset_internalversion.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClientInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clientInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&mobile.Client{}, f.defaultInformer)
}

func (f *clientInformer) Lister() internalversion.ClientLister {
	return internalversion.NewClientLister(f.Informer().GetIndexer())
}
